apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: truenas-redirect
    namespace: truenas-redirect
spec:
    interval: 15m
    chart:
        spec:
            chart: external-service
            version: 16.5.2
            sourceRef:
                kind: HelmRepository
                name: truecharts
                namespace: flux-system
    install:
        createNamespace: true
        crds: CreateReplace
        remediation:
            retries: 3
    upgrade:
        crds: CreateReplace
        remediation:
            retries: 3
    values:
        ingress:
            main:
                enabled: true
                ingressClassName: internal
                annotations:
                    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
                hosts:
                    - host: truenas.${DOMAIN_0}
                integrations:
                    certManager:
                        certificateIssuer: domain-0-le-prod
                        enabled: true
        service:
            main:
                enabled: true
                externalIP: ${TRUENAS_SERVER_IP}
                ports:
                    main:
                        enabled: true
                        port: 8443
                        protocol: https
                type: ExternalIP
