apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: multus
  namespace: flux-system
spec:
  interval: 15m
  path: clusters/main/kubernetes/networking/multus/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: cluster
