# yaml-language-server: $schema=https://github.com/fluxcd-community/flux2-schemas/raw/main/alert-notification-v1beta3.json
apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Alert
metadata:
  name: discord
  namespace: flux-system
spec:
  providerRef:
    name: discord
  eventSeverity: info
  eventSources:
    - kind: HelmRelease
      name: "*"
      namespace: blocky
    - kind: HelmRelease
      name: "*"
      namespace: cert-manager
    - kind: HelmRelease
      name: "*"
      namespace: cloudflared
    - kind: HelmRelease
      name: "*"
      namespace: cloudnative-pg
    - kind: HelmRelease
      name: "*"
      namespace: clusterissuer
    - kind: HelmRelease
      name: "*"
      namespace: default
    - kind: HelmRelease
      name: "*"
      namespace: generic-device-plugin
    - kind: HelmRelease
      name: "*"
      namespace: home-assistant
    - kind: HelmRelease
      name: "*"
      namespace: kube-node-lease
    - kind: HelmRelease
      name: "*"
      namespace: kube-prometheus-stack
    - kind: HelmRelease
      name: "*"
      namespace: kube-public
    - kind: HelmRelease
      name: "*"
      namespace: kube-system
    - kind: HelmRelease
      name: "*"
      namespace: kubernetes-dashboard
    - kind: HelmRelease
      name: "*"
      namespace: kubernetes-reflector
    - kind: HelmRelease
      name: "*"
      namespace: librespeed
    - kind: HelmRelease
      name: "*"
      namespace: longhorn-system
    - kind: HelmRelease
      name: "*"
      namespace: metallb-config
    - kind: HelmRelease
      name: "*"
      namespace: metallb
    - kind: HelmRelease
      name: "*"
      namespace: monitoring
    - kind: HelmRelease
      name: "*"
      namespace: netdata
    - kind: HelmRelease
      name: "*"
      namespace: nginx-external
    - kind: HelmRelease
      name: "*"
      namespace: nginx-internal
    - kind: HelmRelease
      name: "*"
      namespace: openebs
    - kind: HelmRelease
      name: "*"
      namespace: plex
    - kind: HelmRelease
      name: "*"
      namespace: spegel
    - kind: HelmRelease
      name: "*"
      namespace: system-upgrade
    - kind: HelmRelease
      name: "*"
      namespace: tautulli
    - kind: HelmRelease
      name: "*"
      namespace: truenas-redirect
    - kind: HelmRelease
      name: "*"
      namespace: uptime-kuma
    - kind: HelmRelease
      name: "*"
      namespace: volsync
    - kind: HelmRelease
      name: "*"
      namespace: webnut
---
# yaml-language-server: $schema=https://github.com/fluxcd-community/flux2-schemas/raw/main/alert-notification-v1beta3.json
apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Alert
metadata:
  name: discord-kustomization
  namespace: flux-system
spec:
  providerRef:
    name: discord
  eventSeverity: error
  eventSources:
    - kind: Kustomization
      name: "*"