apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:bj1VCp53q3XAx/TnKepj7VwTA80ijCbctWWuGFrnXRYumdXieP4JVhRXSykIhETEhu6KjeqYBqP0Geur2UMLA6sq7Lysm8P+PQvRDWHzIamfFFYlREAIucD1u4jhiifoEfGjsjEMOUoPMa+/LxjRCp9OJfRSBc1h6Jx+B/rjZkOUa1Ppit88R6+2EiAMGjWUGfXvj2ck8NfKEvFTSR5PdfoHy3pHH7SxZl+8Xavyof+ggF4rOoIURaoxtDmtSjp5Ab1mpeGXWxdnm2pTVz/+rdJSm4lndxVMJNFJrUwZaxD6xZLweQmRuZInVkVU/yFmUAjQQysviUrFT+nn477FOzoL0I6fEa42CyjkoLDSl5X0e6+Gteja40+TcYV2co+3,iv:LzcyTUMDBRMkftr7Vm2vEkNF83e/g2pSLQiDAXJ3A5M=,tag:Ok5GLrQ15yPnz3sMI0gd7A==,type:str]
    identity.pub: ENC[AES256_GCM,data:QB7OtVIBha+r278gVwj8naorhEbpwuyiNaotHQYH6C2oSV9LCf44OMyqLphWAcHsF58STh3ppnUAK/JNxCfuMBKzXtdN5NHpfAXuAMxv69NOYOkHKHyUun/Ey2+MRi/7EyIn5mKdo4DlOUw1c9NuTOlmVzYvALBckpt5rJ+1k2Cg5Sz9H5lQa6iGtjIZbu1QFOHjbe8TKwcRNZV29FaO0BUZsToU9lnouAYkJKxIHotbsDI0/YvIO/bxXHE2WH+v2WmQl0RtVWhlE1bzIw==,iv:OpGk0GHVhYQNd59DyNW7ufjTTIRta70mUZQH7OLUzPY=,tag:5N0V1bWGBOUIw0BNcOdk1Q==,type:str]
    known_hosts: ENC[AES256_GCM,data:+QblT1biGkUReqrZhNdOOHjvpe+/7GPhELfGSHEZWymLncqGz9IjtRNKLiwyXDzUNhbujqfXtV/aVoNytrSIfBRJ3JwVCG410qaq7yus9qjKSqw/0Aq6IN+8Le3IdDPMkVMAQ+ioc8JM9yvqkuxU5khneg2YTgMivt+tphEJIRlQl6Q0XIvSZFL6/QyUtOFIVKKe3+1gI9j5vfqoTJMVzWQoERE/1VllKIaD,iv:0ChFtZkVwrb1K6jf39LBV7+xZqGCjpgyn/s9rayc4S8=,tag:wkWdFgulu8ahN25LryWzgg==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age16gcq5u0lsm7a65pgj9zsrjhd8u62myqdsanx4a4lz87l9tzd8yxqzhch73
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0NXlTd096blN3Y04wK0hv
            Ui92M2pZYlZtcnJVRTlFR1VyUGtaRXFpLzJBCnNHY1VZUmEzSVhRYkk0UjZZZTlx
            anBoUzJ2eHJzR25BOFpUdkk4Ordg6VUKLS0tIDNGQkNmZnhsZGh1bjhDWHZiN1Ar
            bEZOc29CcUVGSlU1dnJSaUkzc0VyY1UKMt5+OPUgmX99Gx+noMS/AKsiTDUqz5wL
            t9k26goyya7366DRaMdlSYvMFa/1e/A1FC1pt1DvcAtFE+OkhHHw4Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-20T16:46:58Z"
    mac: ENC[AES256_GCM,data:dSyJsjlR5dRFZqIFIiTdavkUkIJVDkmiLcfOKGdG4M1QNHo9lMTV7mVy8zi9/wFW7hgw6yof3Q6NkakYA7Z80NJQrLwgVvFIsNW4anakhvXTmty3DVnpsx8DOtszv55EOHS1Wn07kpaveKYfVbT0/908ICraPjaXVP6Mh3jUGPw=,iv:sW85U4mq0LArifashPKSRSKHTERWijtprXOXsiCJp4g=,tag:+/Erf3CDpQ5Gy0koK/gb1g==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.1
