apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: multus-cni
  namespace: multus
spec:
    interval: 15m
    chart:
        spec:
            chart: rke2-multus
            version: 4.2.201
            sourceRef:
                kind: HelmRepository
                name: rancher-charts
                namespace: flux-system
            interval: 15m
    timeout: 20m
    maxHistory: 3
    install:
        createNamespace: true
        remediation:
            retries: 3
    upgrade:
        cleanupOnFail: true
        remediation:
            retries: 3
    uninstall:
        keepHistory: false
    values:

    dependsOn:
      - name: cilium
        namespace: kube-system