apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: uptime-kuma
    namespace: uptime-kuma
spec:
    interval: 15m
    chart:
        spec:
            chart: uptime-kuma
            version: 13.7.0
            sourceRef:
                kind: HelmRepository
                name: truecharts
                namespace: flux-system

    values:
        global:
            stopAll: false
        metrics:
            main:
                enabled: false
        values:
        ingress:
            main:
                enabled: true
                ingressClassName: internal
                hosts:
                    - host: uptime-kuma.${DOMAIN_0}
                integrations:
                    certManager:
                        certificateIssuer: domain-0-le-prod
                        enabled: true
       
